import { IToolbarFunction } from './toolbar-function.model';

export interface IAppConfig {
  appVersion: string;
  codelessServicesUrls: IServicesUrls;
  callTimeout: number;
  listHeaderAddFilterContains: boolean;
  listRowFilterStringOperator: number;
  enableLogger: boolean;
  sendingLogsInterval: number;
  sendingLogsBatchSize: number;
  clientLogsMaxSize: number;
  enableTimestampLogger: boolean;
  showAppMessagesInConsole: IAppMessagesConfig;
  logCSPViolations: boolean;
  skipOptimisticCalls: boolean;
  appInsightsSettings: {
    key?: string;
    enable: boolean;
    enableDebug: boolean;
    trackLogs: boolean;
  };
  enableEditableGrid: boolean;
  limitContextMenuDynamicButtons: number;
  tcgSettings: {
    enable: number;
    specificUser: string;
    testCaseGeneratorUploadParameters: {
      functionId: number;
      saveClassId: number;
      targetNavigationId: number;
    };
  };
  callStatusSettings: {
    timeoutBeforeRetry: number;
    numberOfRetries: number;
    waitForCompletion: number;
  };
  removeImageBorder: boolean;
  enableNewStyleNavigationTabs: boolean;
  enableNewTabPosition: boolean;
  enableTabNumbers: boolean;
  customPageTitleDetailsTemplate: string;
  customPageTitleListTemplate: string;
  customPageTitleFunctionIds: number[];
  enableFunctionIdInMainMenuTile: boolean;
  enableFunctionIdAsListTitlePrefix: boolean;
  enableFunctionIdAsSearchResultTitlePrefix: boolean;
  enableFunctionNameAsListTitlePrefix: boolean;
  enableDataCompressionOnPut: boolean;
  showEnumerationNumbers: boolean;
  intranetMode: boolean;
  signalRSupport: boolean;
  authContextConfig: {
    instance: string;
    tenant: string;
    clientId: string;
    postLogoutRedirectUri: string;
  };
  msalApplicationConfigScopes: string[];
  enablePartialPutListSettings: boolean;
  enableListColumnsVirtualisation: boolean;
  appEnvironmentName: boolean | string;
  keepPathOnLogout: boolean;
  networkTimeoutRetryInterval: number;
  notificationApiBaseUrl: string;
  notificationApiScopeName: string;
  useServiceCallsCache: boolean;
  staySignedInAvailable: boolean;
  staySignedInDefaultValue: boolean;
  defaultHomePage: string;
  defaultAuthorizationHeaderName: string;
  displayApplicationHeader: boolean;
  applicationHeaderModernLayout: boolean;
  enableEnvironmentsList: boolean;
  environmentsList_SiteId: string;
  environmentsList_ListId: string;
  environmentsList_RequestsListId: string;
  environmentsList_CacheListId: string;
  enableTreeviewMenu: boolean;
  enableUserFeed: boolean;
  userFeedDays: number;
  enableTeamsChat: boolean;
  applicationHeaderBackground: string;
  menuBackgroundColor: string;
  menuTextColor: string;
  iconSetUrl: string;
  localIconSetUrl: string;
  dashboardRedirectURL: string;
  enableRecentFunctions: boolean;
  recentFunctionsMenuAvailable: boolean;
  recentFunctionsLimit: number;
  quickAddItemsLimit: number;
  authSeparator: string;
  minutesNew: number;
  minutesModified: number;
  defaultLanguage: number;
  defaultLocale: string;
  userSettingsValidityThreshold: number;
  autoHideMessagesTimeout: number;
  sessionIdAvailability: number;
  listAutosizeMaxRows: number;
  listAutosizeHeight: number;
  listAutosizeMinHeight: number;
  listAutosizeMinWidth: number;
  lengthPerChar: number;
  enumerationMaxCharToDisplay: number;
  pageLimit: number;
  pageLimitComboList: number;
  loadAllThreshold: number;
  searchCallInterval: number;
  liveNumbersMaxTimeoutRefreshRate: number;
  liveNumbersDefaultTimeoutRefreshRate: number;
  searchQueryMinLength: number;
  tooltipDisplayDelay: number;
  enableFunctionIdAsPageTitlePrefix: boolean;
  enableFunctionNameAsPageTitle: boolean;
  listNameMaxLength: number;
  signalRConnectionCheckInterval: number;
  filterAssociationDropdownOnOpen: boolean;
  associationDropdownMaximumWidth: number;
  debounceTimeout: number;
  enableCollapsibleSplitLists: boolean;
  RiskMitigation_Disable_DataVersionsClassIdsListTrimming: boolean;
  enableSaveErrorAsTextFile: boolean;
  clearAllAssociationLinksOnComboClear: boolean;
  riskMitigationDisableCircularUnmarkingAttributes: boolean;
  riskMitigationDisableObjectUpdateFromCallStatus: boolean;
  editableGridsLinksUsesKeyboardCombo: boolean;
  riskMitigation_Disable_SingleActionButtonOnDisabledForms: boolean;
  disableContextMenuForceResize: boolean;
  riskMitigation_Disable_FileDeleteDelay: boolean;
  gridImagePreviewerEnabled: boolean;
  gridImagePreviewerWidth: number;
  gridImagePreviewerHeight: number;
  gridImagePreviewerHoverDebounce: number;
  enableProfiler: boolean;
  attributeLinkOpenTarget: string;
  hotjarTracking: {
    enable: boolean;
    id: number;
    snippetVersion: number;
  };
  detailsHeaderMaxHeightPercentage: number;
  enableAutoValidateWaitingOverlay: boolean;
  actionOnDoubleClickEditableList: number;
  actionOnDoubleClickNormalList: number;
  userSnap: {
    enable: boolean;
    key: string;
  };
  msalRenewTokensIntervalMilliSeconds: number;
  msalSendRedirectURILowerCase: boolean;
  renewAccessTokensAutomatically: boolean;
  riskMitigation_Disable_SaveAllFromToolbar: boolean;
  toolbarFunctions: IToolbarFunction[];
  localFileProtocol: string;
}

export interface IServicesUrls {
  rootUrl: string;
  baseUrl: string;
  serverUrl: string;
  systemUrl: string;
  clientUrl: string;
  dataUrl: string;
  customUrl: string;
  adminUrl: string;
  managementUrl: string;
  activityMonitorAPI: string;
}

export interface IAppMessagesConfig {
  log: boolean;
  info: boolean;
  warning: boolean;
  error: boolean;
  debug: boolean;
  timestamp: boolean;
}
